<?php
namespace App\Database\Seeds;

use App\Models\Permission;
use App\Database\Factories\PermissionFactory;
use Illuminate\Database\Seeder;

class PermissionsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     * @return void
     */
    public function run()
    {

        Permission::truncate();

        $permissions = array(
            array(
                "id" => 1,
                "name" => "create",
                "description" => NULL,
                "module_id" => 1,
                "is_primary" => 1,
                "scopes" => "[\"all\", \"none\"]",
                "created_at" => "2024-06-22 10:18:53",
                "updated_at" => "2024-06-22 13:19:54",
            ),
            array(
                "id" => 2,
                "name" => "read",
                "description" => NULL,
                "module_id" => 1,
                "is_primary" => 1,
                "scopes" => "[\"all\", \"owned\", \"none\"]",
                "created_at" => "2024-06-22 10:19:04",
                "updated_at" => "2024-06-22 13:20:04",
            ),
            array(
                "id" => 3,
                "name" => "update",
                "description" => NULL,
                "module_id" => 1,
                "is_primary" => 1,
                "scopes" => "[\"all\", \"owned\", \"none\"]",
                "created_at" => "2024-06-22 10:19:24",
                "updated_at" => "2024-06-22 13:19:58",
            ),
            array(
                "id" => 4,
                "name" => "delete",
                "description" => NULL,
                "module_id" => 1,
                "is_primary" => 1,
                "scopes" => "[\"all\", \"owned\", \"none\"]",
                "created_at" => "2024-06-22 10:19:39",
                "updated_at" => "2024-06-22 13:20:00",
            ),
            array(
                "id" => 5,
                "name" => "modify_user_role",
                "description" => NULL,
                "module_id" => 1,
                "is_primary" => 0,
                "scopes" => "[\"all\", \"none\"]",
                "created_at" => "2024-06-22 10:31:29",
                "updated_at" => "2024-07-21 22:54:14",
            ),
            array(
                "id" => 6,
                "name" => "update_user_permissions",
                "description" => NULL,
                "module_id" => 1,
                "is_primary" => 0,
                "scopes" => "[\"all\", \"none\"]",
                "created_at" => "2024-06-22 11:12:18",
                "updated_at" => "2024-07-21 22:54:14",
            ),
            array(
                "id" => 7,
                "name" => "update_general_settings",
                "description" => NULL,
                "module_id" => 2,
                "is_primary" => 0,
                "scopes" => "[\"all\", \"none\"]",
                "created_at" => "2024-06-22 11:13:11",
                "updated_at" => "2024-07-21 22:54:14",
            ),
            array(
                "id" => 8,
                "name" => "update_seo_settings",
                "description" => NULL,
                "module_id" => 2,
                "is_primary" => 0,
                "scopes" => "[\"all\", \"none\"]",
                "created_at" => "2024-06-22 11:13:53",
                "updated_at" => "2024-07-21 22:54:14",
            ),
            array(
                "id" => 9,
                "name" => "update_translation_settings",
                "description" => NULL,
                "module_id" => 2,
                "is_primary" => 0,
                "scopes" => "[\"all\", \"none\"]",
                "created_at" => "2024-06-22 11:14:29",
                "updated_at" => "2024-07-21 22:54:14",
            ),
            array(
                "id" => 10,
                "name" => "update_language_settings",
                "description" => NULL,
                "module_id" => 2,
                "is_primary" => 0,
                "scopes" => "[\"all\", \"none\"]",
                "created_at" => "2024-06-22 11:15:48",
                "updated_at" => "2024-07-21 22:54:14",
            ),
            array(
                "id" => 11,
                "name" => "create_user_roles",
                "description" => NULL,
                "module_id" => 2,
                "is_primary" => 0,
                "scopes" => "[\"all\", \"none\"]",
                "created_at" => "2024-06-22 11:16:20",
                "updated_at" => "2024-07-21 22:54:14",
            ),
            array(
                "id" => 12,
                "name" => "update_user_roles",
                "description" => NULL,
                "module_id" => 2,
                "is_primary" => 0,
                "scopes" => "[\"all\", \"none\"]",
                "created_at" => "2024-06-22 11:17:10",
                "updated_at" => "2024-07-21 22:54:14",
            ),
            array(
                "id" => 13,
                "name" => "add_permission",
                "description" => NULL,
                "module_id" => 2,
                "is_primary" => 0,
                "scopes" => "[\"all\", \"none\"]",
                "created_at" => "2024-06-26 10:47:25",
                "updated_at" => "2024-07-21 22:54:14",
            ),
            array(
                "id" => 14,
                "name" => "view_permissions",
                "description" => NULL,
                "module_id" => 2,
                "is_primary" => 0,
                "scopes" => "[\"all\", \"none\"]",
                "created_at" => "2024-06-27 00:20:04",
                "updated_at" => "2024-07-21 22:54:14",
            ),
            array(
                "id" => 15,
                "name" => "view_role_permissions",
                "description" => NULL,
                "module_id" => 2,
                "is_primary" => 0,
                "scopes" => "[\"all\", \"none\"]",
                "created_at" => "2024-06-26 21:10:52",
                "updated_at" => "2024-07-21 22:54:14",
            ),
            array(
                "id" => 16,
                "name" => "edit_role_permissions",
                "description" => NULL,
                "module_id" => 2,
                "is_primary" => 0,
                "scopes" => "[\"all\", \"none\"]",
                "created_at" => "2024-06-26 10:48:00",
                "updated_at" => "2024-07-21 22:54:14",
            ),
            array(
                "id" => 17,
                "name" => "add_announcements",
                "description" => NULL,
                "module_id" => 2,
                "is_primary" => 0,
                "scopes" => "[\"all\", \"none\"]",
                "created_at" => "2024-07-03 12:55:10",
                "updated_at" => "2024-07-21 22:54:14",
            ),
            array(
                "id" => 18,
                "name" => "delete_announcements",
                "description" => NULL,
                "module_id" => 2,
                "is_primary" => 0,
                "scopes" => "[\"all\", \"none\"]",
                "created_at" => "2024-07-03 14:05:12",
                "updated_at" => "2024-07-21 22:54:14",
            ),
            array(
                "id" => 19,
                "name" => "create",
                "description" => NULL,
                "module_id" => 3,
                "is_primary" => 1,
                "scopes" => "[\"all\", \"none\"]",
                "created_at" => "2024-07-09 09:25:24",
                "updated_at" => "2024-07-21 22:54:14",
            ),
            array(
                "id" => 20,
                "name" => "read",
                "description" => NULL,
                "module_id" => 3,
                "is_primary" => 1,
                "scopes" => "[\"all\", \"owned\", \"none\"]",
                "created_at" => "2024-07-09 09:26:23",
                "updated_at" => "2024-07-21 22:54:14",
            ),
            array(
                "id" => 21,
                "name" => "update",
                "description" => NULL,
                "module_id" => 3,
                "is_primary" => 1,
                "scopes" => "[\"all\", \"owned\", \"none\"]",
                "created_at" => "2024-07-09 09:26:37",
                "updated_at" => "2024-07-21 22:54:14",
            ),
            array(
                "id" => 22,
                "name" => "delete",
                "description" => NULL,
                "module_id" => 3,
                "is_primary" => 1,
                "scopes" => "[\"all\", \"owned\", \"none\"]",
                "created_at" => "2024-07-09 09:26:46",
                "updated_at" => "2024-07-21 22:54:14",
            ),
            array(
                "id" => 23,
                "name" => "create",
                "description" => NULL,
                "module_id" => 4,
                "is_primary" => 1,
                "scopes" => "[\"all\", \"none\"]",
                "created_at" => "2024-07-09 09:30:08",
                "updated_at" => "2024-07-21 22:54:14",
            ),
            array(
                "id" => 24,
                "name" => "read",
                "description" => NULL,
                "module_id" => 4,
                "is_primary" => 1,
                "scopes" => "[\"all\", \"owned\", \"none\"]",
                "created_at" => "2024-07-09 09:30:24",
                "updated_at" => "2024-07-21 22:54:14",
            ),
            array(
                "id" => 25,
                "name" => "update",
                "description" => NULL,
                "module_id" => 4,
                "is_primary" => 1,
                "scopes" => "[\"all\", \"owned\", \"none\"]",
                "created_at" => "2024-07-09 09:30:56",
                "updated_at" => "2024-07-21 22:54:14",
            ),
            array(
                "id" => 26,
                "name" => "delete",
                "description" => NULL,
                "module_id" => 4,
                "is_primary" => 1,
                "scopes" => "[\"all\", \"none\"]",
                "created_at" => "2024-07-09 09:31:06",
                "updated_at" => "2024-07-21 22:54:14",
            ),
            array(
                "id" => 27,
                "name" => "create",
                "description" => NULL,
                "module_id" => 5,
                "is_primary" => 1,
                "scopes" => "[\"all\", \"none\"]",
                "created_at" => "2024-07-09 09:34:00",
                "updated_at" => "2024-07-21 22:54:14",
            ),
            array(
                "id" => 28,
                "name" => "read",
                "description" => NULL,
                "module_id" => 5,
                "is_primary" => 1,
                "scopes" => "[\"all\", \"owned\", \"none\"]",
                "created_at" => "2024-07-09 09:34:32",
                "updated_at" => "2024-07-21 22:54:14",
            ),
            array(
                "id" => 29,
                "name" => "update",
                "description" => NULL,
                "module_id" => 5,
                "is_primary" => 1,
                "scopes" => "[\"all\", \"owned\", \"none\"]",
                "created_at" => "2024-07-09 09:34:51",
                "updated_at" => "2024-07-21 22:54:14",
            ),
            array(
                "id" => 30,
                "name" => "delete",
                "description" => NULL,
                "module_id" => 5,
                "is_primary" => 1,
                "scopes" => "[\"all\", \"none\"]",
                "created_at" => "2024-07-09 09:35:11",
                "updated_at" => "2024-07-21 22:54:14",
            ),
            array(
                "id" => 31,
                "name" => "create_blog_categories",
                "description" => NULL,
                "module_id" => 3,
                "is_primary" => 0,
                "scopes" => "[\"all\", \"none\"]",
                "created_at" => "2024-07-09 09:39:02",
                "updated_at" => "2024-07-21 22:54:14",
            ),
            array(
                "id" => 32,
                "name" => "view_blog_categories",
                "description" => NULL,
                "module_id" => 3,
                "is_primary" => 0,
                "scopes" => "[\"all\", \"none\"]",
                "created_at" => "2024-07-09 09:39:27",
                "updated_at" => "2024-07-21 22:54:14",
            ),
            array(
                "id" => 33,
                "name" => "update_blog_categories",
                "description" => NULL,
                "module_id" => 3,
                "is_primary" => 0,
                "scopes" => "[\"all\", \"none\"]",
                "created_at" => "2024-07-09 09:40:21",
                "updated_at" => "2024-07-21 22:54:14",
            ),
            array(
                "id" => 34,
                "name" => "delete_blog_categories",
                "description" => NULL,
                "module_id" => 3,
                "is_primary" => 0,
                "scopes" => "[\"all\", \"none\"]",
                "created_at" => "2024-07-09 09:40:39",
                "updated_at" => "2024-07-21 22:54:14",
            ),
            array(
                "id" => 35,
                "name" => "view_roles",
                "description" => NULL,
                "module_id" => 2,
                "is_primary" => 0,
                "scopes" => "[\"all\", \"none\"]",
                "created_at" => "2024-07-21 15:08:30",
                "updated_at" => "2024-07-21 22:54:14",
            ),
            array(
                "id" => 36,
                "name" => "view_modules",
                "description" => NULL,
                "module_id" => 2,
                "is_primary" => 0,
                "scopes" => "[\"all\", \"none\"]",
                "created_at" => "2024-07-21 16:27:45",
                "updated_at" => "2024-07-21 22:54:14",
            ),
            array(
                "id" => 37,
                "name" => "add_module",
                "description" => NULL,
                "module_id" => 2,
                "is_primary" => 0,
                "scopes" => "[\"all\", \"none\"]",
                "created_at" => "2024-07-21 16:40:44",
                "updated_at" => "2024-07-21 22:54:14",
            ),
            array(
                "id" => 38,
                "name" => "edit_module",
                "description" => NULL,
                "module_id" => 2,
                "is_primary" => 0,
                "scopes" => "[\"all\", \"none\"]",
                "created_at" => "2024-07-21 16:40:53",
                "updated_at" => "2024-07-21 22:54:14",
            ),
        );

        foreach($permissions as $permission) {
            Permission::create($permission);
        }
        
    }
}
